# version: 2
# updates:
#   - package-ecosystem: 'npm'
#     directory: '/'
#     schedule:
#       interval: 'weekly'
#       time: '18:00'
#       timezone: 'Asia/Tokyo'
#   - package-ecosystem: 'github-actions'
#     directory: '/'
#     schedule:
#       interval: 'weekly'
#       time: '18:00'
#       timezone: 'Asia/Tokyo'
