services:
  unleash:
    container_name: unleash
    image: unleashorg/unleash-server:latest
    ports:
      - 4242:4242
    environment:
      DATABASE_URL: postgres://user:postgres@postgres:5432/db
      DATABASE_SSL: false
      LOG_LEVEL: warn
      INIT_CLIENT_API_TOKENS: default:development.unleash-insecure-api-token
    depends_on:
      postgres:
        condition: service_healthy
    command: ["node", "index.js"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 10s
      timeout: 1m
      retries: 5
      start_period: 15s
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: pg_isready --username=user --dbname=db --host=127.0.0.1 --port=5432
      interval: 10s
      timeout: 1m
      retries: 5
      start_period: 10s
