// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dev.nazna.examplespringmodulith.user.repository

import java.sql.SQLException

interface Queries {
    @Throws(SQLException::class)
    fun findUser(id: Long): User?

}

