server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: spring-boot-otel
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  lifecycle:
    timeout-per-shutdown-phase: 1s
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      enabled: true

logging:
  level:
    org.apache: off
    org.springframework.boot.web.embedded.tomcat: off
    org.springframework.boot.web.servlet.context: off
    org.springframework.web.servlet.DispatcherServlet: off

otel:
  resource:
    attributes:
      deployment:
        environment: local
      service:
        name: spring-boot-otel
        namespace: sandbox
