name: check-status
on: push
env:
  CI: true
  TZ: Asia/Tokyo
permissions:
  contents: read
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'gradle'
      - run: ./gradlew spotlessCheck
  build:
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'gradle'
      - run: ./gradlew clean build