server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: example-otel-mlt
  datasource:
    url: jdbc:postgresql://postgres:5432/sandbox
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  lifecycle:
    timeout-per-shutdown-phase: 1s
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://opentelemetry-collector:4318/v1/metrics
    tracing:
      endpoint: http://opentelemetry-collector:4318/v1/traces

logging:
  level:
    org.apache: off
    org.springframework.boot.web.embedded.tomcat: off
    org.springframework.boot.web.servlet.context: off
    org.springframework.web.servlet.DispatcherServlet: off

otel:
  exporter:
    otlp:
      endpoint: http://opentelemetry-collector:4318
  resource:
    attributes:
      service:
        name: dice
        version: 0.0.1
  instrumentation:
    micrometer:
      enabled: true
