name = "wisp_echo"
version = "1.0.0"
description = "Hello, Gleam lang with Wisp"
gleam = ">= 1.5.1"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 1.2.0 and < 2.0.0"
mist = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 0.28.0 and < 1.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
