CREATE TABLE IF NOT EXISTS users (
  id             SERIAL    NOT NULL PRIMARY KEY,
  name           TEXT      NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at     TIMESTAMP NULL     DEFAULT NULL,
  deleted_reason TEXT      NULL     DEFAULT NULL
);
