version: "3"
services:
  backend:
    container_name: backend
    build: ./docker/backend
    ports:
      - 8082:8082
    tty: true
    volumes:
      - ./backend:/app
  database:
    container_name: database
    image: mysql
    environment:
      MYSQL_DATABASE: ema
      MYSQL_USER: user
      MYSQL_PASSWORD: password

