CREATE TABLE
  IF NOT EXISTS places (
    place_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
    PRIMARY KEY (place_id)
  );

CREATE TABLE
  IF NOT EXISTS reviews (
    review_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    place_id INTEGER NOT NULL,
    body VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
    PRIMARY KEY (review_id)
  );
