// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dev.nazna.examplespringmodulith.user.repository

import java.time.OffsetDateTime

data class User (
  val id: Int,
  val name: String,
  val createdAt: OffsetDateTime,
  val updatedAt: OffsetDateTime
)

