CREATE TABLE IF NOT EXISTS users
(
  id         INTEGER     NOT NULL GENERATED ALWAYS AS IDENTITY,
  name       VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
