package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"example-gqlgen-sqlc/domain"
	"fmt"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (domain.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*domain.User, error) {
	return r.userUsecase.FindUser(ctx, userID)
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, taskID string) (*domain.Task, error) {
	panic(fmt.Errorf("not implemented: Task - task"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
