// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package dao

import (
	"context"
)

const findUser = `-- name: FindUser :one
SELECT
  user_id,
  username,
  created_at,
  updated_at
FROM
  user
WHERE
  user_id = ?
LIMIT
  1
`

func (q *Queries) FindUser(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, findUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
