CREATE TABLE IF NOT EXISTS posts
(
  id         INTEGER     NOT NULL GENERATED ALWAYS AS IDENTITY,
  user_id    INTEGER     NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);
