[tools]
duckdb = "1.3.2"
"npm:opensrc" = "latest"
python = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true

[tasks.setup]
quiet = true
run = """
curl -LO https://github.com/amazon-science/esci-data/raw/refs/heads/main/shopping_queries_dataset/shopping_queries_dataset_products.parquet -o products.parquet
"""

[tasks.indexer]
run = "uv run --env-file=.env src/indexer/main.py"

[tasks.retriever]
run = "adk web src/retriever"

[tasks.check]
run = "uv format"
