// Code generated by sqlc. DO NOT EDIT.
// source: users-find-by-id.sql

package persistence

import (
	"context"
)

const selectUserById = `-- name: SelectUserById :one
SELECT
  id,
  name,
  created_at,
  updated_at,
  deleted_at,
  deleted_reason
FROM
  users
WHERE
  id = ?
`

func (q *Queries) SelectUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
	)
	return i, err
}
